services:
  app:
    build: .
    tty: true
    environment:
      PORT: 5000
    container_name: unirecognition-api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - server-side
    ports:
      - "5000:5000"
    stop_signal: SIGKILL

  db:
    image: postgres:17
    container_name: unirecognition-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - server-side
    ports:
      - "5432:5432"
    stop_signal: SIGKILL

volumes:
  db-data: {}

networks:
  client-side:
      driver: bridge
  server-side: {}